wechat:
  sns:
    oauth2:
      access_token:
        url: https://api.weixin.qq.com/sns/oauth2/access_token
        appid: wx7287a60bb700fd21
        secret: 1ef8755f92bebae8ad7bab432ba29cbf
        grant_type: authorization_code
    userinfo:
      url: https://api.weixin.qq.com/sns/userinfo

alipay:
  client:
    url: https://openapi.alipay.com/gateway.do
    app_id: 2021001187673494
    app_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDBiCQPNSrrhje5LaC7HnP70ssc/HzEp7a6XUYDPmPZAzsVUqdkkEoZlDKWneMXvEmEyRGXKZ8K4Yine7UeG5vpyr/Si3z2xA5KpsB6LdjalxkkE2qrPMUZ/HREPmN5Y+foNb5U5i+YdoJYMXxLCd00TxEmSw6YTThY7IWG6XE5eU5x+y+P3lx6/jItJNmCYs4ynT02js7YhicnWLmCwIXN4v9v77X2JP8sLcPgJwybR31/x9MJ2y6zOmugTKP61bE52P+HEDXHA65pRQcJ9RrwB04a3TPLfq4eKIxwjZIOteQfhW7UbaZ17IJbeRQ8qavAymTc9LxD8kowbGCi8+ZxAgMBAAECggEAEau8nybbpGW88MuZwXwmWvgEU8E6IzqtFJcvrVwlAcupuWiyoBwMqAlAFUCVW7V1gQpa8NJ8EyJEuAYzo2wh8Fby7OaPoniEVYykRoOpKUxin0imlLwXwyep9hE8Q/k7U5iUqGvcLK+ldygNkUx1RjFx/20bCA0E+Bmgl5D5JaYlI8m4zI/h5KTZ4/gGy0BMsVLJdfZrXY4FhHF7PtGvU4WhVfA9vnsyXaUZq0dSqoDsKU8PjSGDyv8GCohoq30aaYPS7wTzAYzwL39sAQsLviIFIN0UOfWMEOobJkv7rZj19Fht35XrxIMCJoqGNsj6zvSebucoiHzj3zAkWN9KAQKBgQDu1+p8C7STEOcc1eHSXwHh0uoH+MJDTQWXufX30516/VxpfW7pgaFEAVKUBzG33tf09LaWpJmy8VKHd2sbec6RzC5OpJwTGzIhj4sy0KSGacAUsqxHtRSYPUki1Ou6VH8Y63meJzOdg4Wdvlgz5nVVdTX7QBdjciwKcJdeizcHfQKBgQDPbv2udLumT8p7oyiOhwLO3wmtVnIipcu5E2r72mQl+LLesWivE55j29H5waSmHMunl5ezqPmSfrSCjZFPhkG8lBLiuxmyIuwrzhs4I8s94sfE64TloEN/A4SLIXzLrmEUjycZkw295BR4DjY8AK1si0MR2NxYJmteCOanWqmVBQKBgGC3GgKFEugCjjOFAF6Zjj+NkqsLtk5eYAdijBGApWJqOgOVgVYY4d6R0oiSqTVVjYlplo5FtN9bDRpB5yNHHbi4P4Ak8/ZgqtogMDOxfQ3YwKkg+NZIo0BKgNUT9yiKkrTalXLPWP1Nhsurijfp+FVUkzlcaJwiXWcU1Ja6NNxZAoGBAIFUpUxJMdous4NEpfu/R8vtmd3+IOljT9KTvcdLUdeu6O8Z07gc1ktSeedriZmcKInUZVw5xWlGIIupcmkPvxqxg9jjaND9Hxzsw2HMR2LNa1pmsZRtyMd/TPtmJKXlkle8LVevrQixFOYJjlz42yfq6CVPfYpkYdreV9kOGN91AoGAGJjsqxYhI6Fp305sh9rmKREPrqrT7QVuuLZ+7NjjSgSU+nPjgY2Nk2OYe759aGKUREE/LyFy/L60ffxu2GSMHsfc/PVsH4E9AmEU5ZpgM3Zqxfa3gNantt2fmr1bb/iskvaqZ+wp+K3kudfDVR47zHaIFWmJlyqNqu6rkIkktCE=
    format: json
    charset: UTF-8
    alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq0wKq8EI42tTY77JD41lnrtfWH2OFY0eknyKIu+5iU7gg8QRXV/7qmS/k13VLig5cLKy7soc+bRY0HVzSMvx4PymbVQeYbF7SUZdvVt+GJtXL7RKXq2uNmQ8dKTQaCVCYVcLk+hYGIJY92L+0R38uMwd4aoLFiiXkP4mCLNIaVQn6egLIV2CvtIqxvrHFmTblcp8bDP/1p13pRS9aUzdyjTDIzlMZkdaxe6T9rXvNFaLq3olq7Pwocb94WR6mfzANUa8wX0w4XUCPbeTjvNHmm6DYWOdIlGnqikFDunNl4pH1sJhta1y9GzfQuAswepBS7kOf5nR0FswsL7SqMk7jwIDAQAB
    sign_type: RSA2

